version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis-win
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/usaboo/Downloads/PCISUTKSD/personal/projects/trader_bot/data:/data
    command: ["redis-server", "--appendonly", "yes"]